name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: SonarQube Scan
        run: mvn sonar:sonar -Dsonar.projectKey=springboot-crud-demo -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqa_32ef4e92653420bf82dccb6aec747cea41f3a5f4

      - name: Build Docker image
        run: docker build -t springboot-crud-demo .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 springboot-crud-demo