name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: SonarQube Scan
        run: mvn sonar:sonar -Dsonar.projectKey=springboot-thymeleaf-crud-web-app -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqp_6088ea1d5fe2920c62dfc5719cd59e2d0f0f7174

      - name: Build Docker image
        run: docker build -t springboot-thymeleaf-crud-web-app .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 springboot-thymeleaf-crud-web-app

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: wissem.lemsi@esprit.tn
          password: Ronaldo@23
          subject: CI/CD Pipeline Completed
          body: The CI/CD pipeline has completed successfully.
          to: oussema.trojet1@gmail.com
          from: wissem.lemsi@esprit.tn